# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yRwsgutGvS7lmtL4NiHbTHsIcysDlBl4
"""

from mpl_toolkits.mplot3d import axes3d
import numpy as np
import matplotlib.pyplot as plt

# plot skew lines
fig = plt.figure()
ax = plt.axes(projection='3d')

# set axis labels
#ax.set_xlabel('x-axis')
#ax.set_ylabel('y-axis')
#ax.set_zlabel('z-axis')

# set axis limits
ax.set_xlim(-5, 5)
ax.set_ylim(-5, 5)
ax.set_zlim(-5, 5)

# plot line 1
ax.plot3D([3, 7, -7], [0, -2, 5], [1, 3, -4], label = '$L_1$')
# plot line 2
ax.plot3D([5, -4], [-4, 11], [1, -5], label='$L_2$')

# plot point P on line 1
ax.plot3D([1.85], [0.58], [0.42], marker='o', label='$P(1.85, 0.58, 0.42)$')
ax.text(1.85, 0.58, 0.42, 'P', color='blue')

# plot point Q on line 2
ax.plot3D([2.36], [0.41], [-0.76], marker='o',label='$Q(2.36, 0.41, -0.76)$')
ax.text(2.36, 0.41, -0.76, 'Q', color='b')

# draw a line between P and Q
ax.plot3D([1.85, 2.36],[0.58, 0.41],[0.42, -0.76])

plt.legend()

# rotate view by angle 30 degrees
ax.view_init(azim=30)

plt.show()