# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12gkooM-EmPiDZaTDk8-VR7dRPSOIOz77
"""

from mpl_toolkits.mplot3d import axes3d
import numpy as np
import matplotlib.pyplot as plt

# plot skew lines
fig = plt.figure()
ax = plt.axes(projection='3d')

# set axis labels
#ax.set_xlabel('x-axis')
#ax.set_ylabel('y-axis')
#ax.set_zlabel('z-axis')

# set axis limits
ax.set_xlim(-5, 5)
ax.set_ylim(-5, 5)
ax.set_zlim(-5, 5)

# plot line 1
ax.plot3D([3, 7, -7], [0, -2, 5], [1, 3, -4], label = '$L_1$')
# plot line 2
ax.plot3D([5, -4], [-4, 11], [1, -5], label='$L_2$')

# plot point P on line 1
ax.plot3D([0.763], [1.119], [0.119], marker='o', label='$P(0.763, 1.119, 0.119)$')
ax.text(0.763, 1.119, 0.119, 'P', color='blue')

# plot point Q on line 2
ax.plot3D([0.729], [3.119], [-1.847], marker='o',label='$Q(0.729, 3.119, -1.847)$')
ax.text(0.729, 3.119, -1.847, 'Q', color='b')

# draw a line between P and Q
#ax.plot3D([1, 2], [1,1], [0, -1])
ax.plot3D([0.763, 0.729],[1.119, 3.119],[0.119, -1.847])

plt.legend()

# rotate view by angle 30 degrees
ax.view_init(azim=-30)

plt.show()