# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jkAO9sexz4M55_NbQWuM9tqbf6-NgLLe
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.arange(-5,6)

x1 = 1
x2 = 0
fig, ax = plt.subplots()
plt.plot(x1,'o',label='$x_1 = 1$')
plt.plot(x2,'o',label='$x_2 = 0$')

plt.plot(x,x, label = '$f_1(x) = x$')
plt.plot(x,1-x, label = '$f_2(x) = 1-x$')

plt.plot(x1, 'o', label='$f_1(x_1) = 1$')
plt.plot(1-x1, 'o', label='$f_2(x_1) = 0$')

plt.plot(x2, 'o', label='$f_1(x_2) = 0$')
plt.plot(1-x2, 'o', label='$f_2(x_2) = 1$')

ax.spines['left'].set_position('zero')
ax.spines['bottom'].set_position('zero')
ax.spines['top'].set_color('none')
ax.spines['right'].set_color('none')

plt.xlim([-5,5])
plt.xlabel('x')
plt.ylabel('f(x)')
plt.grid(True)
plt.legend(loc='best')
plt.show()