# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTL6MayQWD-2ih_Zbov6ppNQt-tDmMOV
"""

import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = plt.axes(projection='3d')

ax.set_xlim(-5,5)
ax.set_ylim(0,6)
ax.set_zlim(-2,7)

ax.set_xlabel('x-axis')
ax.set_ylabel('y-axis')
ax.set_zlabel('z-axis')

# plot vector a = [-2 4 5]
handle_a = ax.quiver(0,0,0,-2,4,5, color='g')

# plot vector b = [3 5 6]
handle_b = ax.quiver(0,0,0,3,5,6, color='r')

# plot equation x-y+z=-1
x = np.linspace(-5,5)
y = np.linspace(0,6)
z = y-x-1

ax.plot3D(x,y,z)

plt.show()